### ISSUE TITLE
Module not found error after pip install

### ISSUE THREAD

**Issue by SupreethRao99** [lhenault/simpleAI#13]
Hello, I've installed time library through pip ```pip install simple_ai_server``` and I'm getting the following error ```ModuleNotFoundError: No module named 'simple_ai.api'``` could you suggest a fix for this issue. Thanks

**Comment by lhenault** [comment]
Hi thanks for the feedback! The latest release on PyPi is actually a bit outdated at this point. 

I should tag and upload a newer version in the upcoming days, as we’ve fixed a few issues, and added new features, but was waiting for some to be merged.

The easiest fix here is to install from the repository:

`pip install git+https://github.com/lhenault/simpleAI.git`

**Comment by SupreethRao99** [comment]
Hi, thank you @lhenault,i will definitely do that.

**Comment by SupreethRao99** [comment]
slightly off topic, but while running the container, I see ```"[::]:50051"``` as the default port. does this expose the port 50051 on the localhost, as I'm having a bit of trouble getting the completions to work

**Comment by lhenault** [comment]
That’s correct, the provided function to launch a gRPC server uses port 50051 by default. If you’re exposing a model through Docker you indeed have to open and redirect the 50051 port (which is done through the `-p 50051:50051` argument in the docker command in the examples `README`).

**Comment by SupreethRao99** [comment]
Thanks again @lhenault , another observation I made is that is that python>3.11  is required to run ```simple_ai serve [--host 127.0.0.1] [--port 8080]``` as it has a dependency on tomllib. am I doing something wrong ? the error occurred while installing from source as well as installing from pip. Thank You!

**Comment by lhenault** [comment]
This should have been addressed [here](https://github.com/lhenault/simpleAI/pull/10/commits/7edba2dfdcd743262265a5560f3ba5c84f3c2c08), so it shouldn’t occur anymore if you install from source.

**Comment by SupreethRao99** [comment]
I was able to get to work, by switching to python 3.11 where tomllib is supported. it seems like I'm on the home stretch now, but when I send a POST request, I'm getting the following error

```
Traceback (most recent call last):
  File "<conda-env-path>/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<conda-env-path>/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<conda-env-path>/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "<conda-env-path>/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "<conda-env-path>/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "<conda-env-path>/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "<conda-env-path>/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "<conda-env-path>/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "<conda-env-path>/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "<conda-env-path>/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "<conda-env-path>/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "<conda-env-path>/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "<conda-env-path>/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "<conda-env-path>/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<conda-env-path>/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<conda-env-path>/lib/python3.11/site-packages/simple_ai/server.py", line 51, in complete
    predictions = llm.complete(
                  ^^^^^^^^^^^^^
  File "<conda-env-path>/lib/python3.11/site-packages/simple_ai/models.py", line 35, in complete
    return lm_client.run(
           ^^^^^^^^^^^^^^
  File "<conda-env-path>/lib/python3.11/site-packages/simple_ai/clients/completion/client.py", line 41, in run
    with grpc.insecure_channel(url) as channel:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<conda-env-path>/lib/python3.11/site-packages/grpc/__init__.py", line 1964, in insecure_channel
    return _channel.Channel(target, () if options is None else options, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<conda-env-path>/lib/python3.11/site-packages/grpc/_channel.py", line 1649, in __init__
    _common.encode(target), _augment_options(core_options, compression),
    ^^^^^^^^^^^^^^^^^^^^^^
  File "<conda-env-path>/lib/python3.11/site-packages/grpc/_common.py", line 74, in encode
    return s.encode('utf8')
           ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode'
```
Could you help me with this?  Thank you @lhenault

**Comment by lhenault** [comment]
Looks like we’re moving forward! :)

I’d need to have a look at your toml config and request to help further here. It looks like some parameter is passed as `None` instead of a string and cannot be encoded, so my best guess is a parameter you’ve forgotten.

**Comment by SupreethRao99** [comment]
hey, here's my toml file 

```
[vicuna-13b]
    [vicuna-13b.metadata]
        owned_by    = 'Meta'
        permission  = []
        description = 'Instruction Tuned LLaMA running on 8bit precision'
    [model.network]
        type = 'gRPC'
        url = 'localhost:50051'


````

**Comment by SupreethRao99** [comment]
Hey, @lhenault,  Here's my model.py
```
import logging
from dataclasses import dataclass
from typing import Union

from simple_ai.api.grpc.completion.server import LanguageModel
from transformers import GenerationConfig
from transformers import LlamaForCausalLM, AutoTokenizer

@dataclass(unsafe_hash=True)
class VicunaModel(LanguageModel):
    try:
        tokenizer = AutoTokenizer.from_pretrained('./vicuna-13b')
    except Exception as ex:
        logging.exception(f"Could not load tokenizer: {ex}")
        tokenizer = None
    try:
        model = LlamaForCausalLM.from_pretrained(
            './vicuna-13b',
            load_in_8bit=True,
            device_map="auto"
        )
    except Exception as ex:
        logging.exception(f"Could not load pretrained LlaMa model: {ex}")
        model = None

    def complete(
        self,
        prompt: str = "</s>",
        suffix: str = "",
        max_tokens: int = 512,
        temperature: float = 1.0,
        top_p: float = 1.0,
        n: int = 1,
        stream: bool = False,
        logprobs: int = 0,
        echo: bool = False,
        stop: Union[str, list] = "",
        presence_penalty: float = 0.0,
        frequence_penalty: float = 0.0,
        best_of: int = 0,
        logit_bias: dict = {},
    ) -> str:
        generation_config = GenerationConfig(
            temperature=temperature,
            top_p=top_p,
            num_beams=2,
            
        )

        inputs = self.tokenizer(prompt, return_tensors="pt")
        input_ids = inputs["input_ids"]
        input_ids = input_ids.cuda()

        output = self.model.generate(
            input_ids=input_ids,
            generation_config=generation_config,
            return_dict_in_generate=True,
            output_scores=True,
            max_new_tokens=max_tokens,
        )
        results = []
        for sequence in output.sequences:
            results.append(self.tokenizer.decode(sequence))
        return results[0]
```
and my server.py
```
import logging

from model import VicunaModel as Model
from simple_ai.api.grpc.completion.server import LanguageModelServicer, serve

if __name__ == "__main__":
    import argparse

    logging.basicConfig(level=logging.INFO)

    parser = argparse.ArgumentParser()
    parser.add_argument("-a", "--address", type=str, default="[::]:50051")
    args = parser.parse_args()

    logging.info(f"Starting gRPC server on {args.address}")

    model_servicer = LanguageModelServicer(model=Model())
    serve(address=args.address, model_servicer=model_servicer)
```

**Comment by SupreethRao99** [comment]
thanks @lhenault , had to fix my toml file, to this

```
[vicuna-13b]
    [vicuna-13b.metadata]
        owned_by    = 'Meta'
        permission  = []
        description = 'Instruction Tuned LLaMA running on 8bit precision'
    [vicuna-13b.network]
        type = 'gRPC'
        url = 'localhost:50051'
```

worked perfectly,
